spring:
  profiles:
    active: local
  application:
    name: account-service-api
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8585

spring.jpa.hibernate.ddl-auto: none
spring.jpa.open-in-view: true

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:account-service
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  flyway:
    url: jdbc:h2:mem:account-service
    user: sa
    password:
    locations: classpath:db/migration
    baseline-on-migrate: true
#    enabled: false


